# Generated by Django 2.2.5 on 2020-03-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200301_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
