# Generated by Django 2.2.5 on 2020-03-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200303_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='about_me',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
