# Generated by Django 2.2.5 on 2020-03-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200304_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
